---
development:
  secret_key_base: 4f652b992e258c03478b463380b23bca70cb9758a3b26c6dd3f5c31a46fd042548ff0176cc6ad3a5e1077c675c6f8bb305a14121ca5c68568318461507d2c94b

test:
  secret_key_base: 8302ca4ce082fa7e37dc5f8c5915609ee6e7c451fb8451aa2c87258f1db6d68759a2cbf50f358bf26847b57525b2caec1d916a7c51ed710b314067b44f25f864
